server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employeeModule
          uri: lb://service1
          predicates:
            - Path=/employee/**
        - id: consumerModule
          uri: lb://service2
          predicates:
            - Path=/consumer/**
